# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ni9234.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLayout,
    QLineEdit, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QVBoxLayout, QWidget)

class Ui_NI9234(object):
    def setupUi(self, NI9234):
        if not NI9234.objectName():
            NI9234.setObjectName(u"NI9234")
        NI9234.setEnabled(True)
        NI9234.resize(1280, 720)
        self.ChannelOption_GroupBox = QGroupBox(NI9234)
        self.ChannelOption_GroupBox.setObjectName(u"ChannelOption_GroupBox")
        self.ChannelOption_GroupBox.setGeometry(QRect(10, 220, 210, 150))
        self.Ch4_Frame = QFrame(self.ChannelOption_GroupBox)
        self.Ch4_Frame.setObjectName(u"Ch4_Frame")
        self.Ch4_Frame.setGeometry(QRect(10, 110, 190, 32))
        self.Ch4_Frame.setFrameShape(QFrame.NoFrame)
        self.Ch4_Frame.setFrameShadow(QFrame.Plain)
        self.Ch4_CheckBox = QCheckBox(self.Ch4_Frame)
        self.Ch4_CheckBox.setObjectName(u"Ch4_CheckBox")
        self.Ch4_CheckBox.setGeometry(QRect(5, 5, 75, 22))
        self.Ch4_ComboBox = QComboBox(self.Ch4_Frame)
        self.Ch4_ComboBox.addItem("")
        self.Ch4_ComboBox.addItem("")
        self.Ch4_ComboBox.addItem("")
        self.Ch4_ComboBox.setObjectName(u"Ch4_ComboBox")
        self.Ch4_ComboBox.setGeometry(QRect(85, 5, 100, 22))
        self.Ch2_Frame = QFrame(self.ChannelOption_GroupBox)
        self.Ch2_Frame.setObjectName(u"Ch2_Frame")
        self.Ch2_Frame.setGeometry(QRect(10, 50, 190, 32))
        self.Ch2_Frame.setFrameShape(QFrame.NoFrame)
        self.Ch2_Frame.setFrameShadow(QFrame.Plain)
        self.Ch2_CheckBox = QCheckBox(self.Ch2_Frame)
        self.Ch2_CheckBox.setObjectName(u"Ch2_CheckBox")
        self.Ch2_CheckBox.setGeometry(QRect(5, 5, 75, 22))
        self.Ch2_ComboBox = QComboBox(self.Ch2_Frame)
        self.Ch2_ComboBox.addItem("")
        self.Ch2_ComboBox.addItem("")
        self.Ch2_ComboBox.addItem("")
        self.Ch2_ComboBox.setObjectName(u"Ch2_ComboBox")
        self.Ch2_ComboBox.setGeometry(QRect(85, 5, 100, 22))
        self.Ch3_Frame = QFrame(self.ChannelOption_GroupBox)
        self.Ch3_Frame.setObjectName(u"Ch3_Frame")
        self.Ch3_Frame.setGeometry(QRect(10, 80, 190, 32))
        self.Ch3_Frame.setFrameShape(QFrame.NoFrame)
        self.Ch3_Frame.setFrameShadow(QFrame.Plain)
        self.Ch3_CheckBox = QCheckBox(self.Ch3_Frame)
        self.Ch3_CheckBox.setObjectName(u"Ch3_CheckBox")
        self.Ch3_CheckBox.setGeometry(QRect(5, 5, 75, 22))
        self.Ch3_ComboBox = QComboBox(self.Ch3_Frame)
        self.Ch3_ComboBox.addItem("")
        self.Ch3_ComboBox.addItem("")
        self.Ch3_ComboBox.addItem("")
        self.Ch3_ComboBox.setObjectName(u"Ch3_ComboBox")
        self.Ch3_ComboBox.setGeometry(QRect(85, 5, 100, 22))
        self.Ch1_Frame = QFrame(self.ChannelOption_GroupBox)
        self.Ch1_Frame.setObjectName(u"Ch1_Frame")
        self.Ch1_Frame.setGeometry(QRect(10, 20, 190, 32))
        self.Ch1_Frame.setFrameShape(QFrame.NoFrame)
        self.Ch1_Frame.setFrameShadow(QFrame.Plain)
        self.Ch1_CheckBox = QCheckBox(self.Ch1_Frame)
        self.Ch1_CheckBox.setObjectName(u"Ch1_CheckBox")
        self.Ch1_CheckBox.setGeometry(QRect(5, 5, 75, 22))
        self.Ch1_ComboBox = QComboBox(self.Ch1_Frame)
        self.Ch1_ComboBox.addItem("")
        self.Ch1_ComboBox.addItem("")
        self.Ch1_ComboBox.addItem("")
        self.Ch1_ComboBox.setObjectName(u"Ch1_ComboBox")
        self.Ch1_ComboBox.setGeometry(QRect(85, 5, 100, 22))
        self.Prameters_GroupBox = QGroupBox(NI9234)
        self.Prameters_GroupBox.setObjectName(u"Prameters_GroupBox")
        self.Prameters_GroupBox.setGeometry(QRect(10, 60, 340, 150))
        self.SampleRate_Frame = QFrame(self.Prameters_GroupBox)
        self.SampleRate_Frame.setObjectName(u"SampleRate_Frame")
        self.SampleRate_Frame.setEnabled(True)
        self.SampleRate_Frame.setGeometry(QRect(10, 20, 320, 30))
        self.SampleRate_Frame.setFrameShape(QFrame.NoFrame)
        self.SampleRate_Frame.setFrameShadow(QFrame.Plain)
        self.SampleRate_HorizontalSlider = QSlider(self.SampleRate_Frame)
        self.SampleRate_HorizontalSlider.setObjectName(u"SampleRate_HorizontalSlider")
        self.SampleRate_HorizontalSlider.setGeometry(QRect(140, 5, 100, 20))
        self.SampleRate_HorizontalSlider.setMinimum(3200)
        self.SampleRate_HorizontalSlider.setMaximum(51200)
        self.SampleRate_HorizontalSlider.setValue(12800)
        self.SampleRate_HorizontalSlider.setSliderPosition(12800)
        self.SampleRate_HorizontalSlider.setOrientation(Qt.Horizontal)
        self.SampleRate_SpinBox = QSpinBox(self.SampleRate_Frame)
        self.SampleRate_SpinBox.setObjectName(u"SampleRate_SpinBox")
        self.SampleRate_SpinBox.setGeometry(QRect(250, 5, 60, 20))
        self.SampleRate_SpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SampleRate_SpinBox.setSpecialValueText(u"")
        self.SampleRate_SpinBox.setMinimum(12800)
        self.SampleRate_SpinBox.setMaximum(51200)
        self.SampleRate_Label = QLabel(self.SampleRate_Frame)
        self.SampleRate_Label.setObjectName(u"SampleRate_Label")
        self.SampleRate_Label.setGeometry(QRect(10, 5, 120, 20))
        self.SampleRate_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SampleRate_Label.setIndent(-1)
        self.DownSample_Frame = QFrame(self.Prameters_GroupBox)
        self.DownSample_Frame.setObjectName(u"DownSample_Frame")
        self.DownSample_Frame.setEnabled(True)
        self.DownSample_Frame.setGeometry(QRect(10, 110, 320, 30))
        self.DownSample_Frame.setFrameShape(QFrame.NoFrame)
        self.DownSample_Frame.setFrameShadow(QFrame.Plain)
        self.DownSample_HorizontalSlider = QSlider(self.DownSample_Frame)
        self.DownSample_HorizontalSlider.setObjectName(u"DownSample_HorizontalSlider")
        self.DownSample_HorizontalSlider.setGeometry(QRect(140, 5, 100, 20))
        self.DownSample_HorizontalSlider.setMinimum(0)
        self.DownSample_HorizontalSlider.setMaximum(5)
        self.DownSample_HorizontalSlider.setSliderPosition(5)
        self.DownSample_HorizontalSlider.setOrientation(Qt.Horizontal)
        self.DownSample_SpinBox = QSpinBox(self.DownSample_Frame)
        self.DownSample_SpinBox.setObjectName(u"DownSample_SpinBox")
        self.DownSample_SpinBox.setGeometry(QRect(250, 5, 60, 20))
        self.DownSample_SpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.DownSample_SpinBox.setSpecialValueText(u"")
        self.DownSample_SpinBox.setMinimum(0)
        self.DownSample_SpinBox.setMaximum(100)
        self.DownSample_Label = QLabel(self.DownSample_Frame)
        self.DownSample_Label.setObjectName(u"DownSample_Label")
        self.DownSample_Label.setGeometry(QRect(10, 5, 120, 20))
        self.DownSample_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.DownSample_Label.setIndent(-1)
        self.FrameDuration_Frame = QFrame(self.Prameters_GroupBox)
        self.FrameDuration_Frame.setObjectName(u"FrameDuration_Frame")
        self.FrameDuration_Frame.setEnabled(True)
        self.FrameDuration_Frame.setGeometry(QRect(10, 50, 320, 30))
        self.FrameDuration_Frame.setFrameShape(QFrame.NoFrame)
        self.FrameDuration_Frame.setFrameShadow(QFrame.Plain)
        self.FrameDuration_HorizontalSlider = QSlider(self.FrameDuration_Frame)
        self.FrameDuration_HorizontalSlider.setObjectName(u"FrameDuration_HorizontalSlider")
        self.FrameDuration_HorizontalSlider.setGeometry(QRect(140, 5, 100, 20))
        self.FrameDuration_HorizontalSlider.setMinimum(75)
        self.FrameDuration_HorizontalSlider.setMaximum(1000)
        self.FrameDuration_HorizontalSlider.setValue(200)
        self.FrameDuration_HorizontalSlider.setSliderPosition(200)
        self.FrameDuration_HorizontalSlider.setOrientation(Qt.Horizontal)
        self.FrameDuration_SpinBox = QSpinBox(self.FrameDuration_Frame)
        self.FrameDuration_SpinBox.setObjectName(u"FrameDuration_SpinBox")
        self.FrameDuration_SpinBox.setGeometry(QRect(250, 5, 60, 20))
        self.FrameDuration_SpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.FrameDuration_SpinBox.setSpecialValueText(u"")
        self.FrameDuration_SpinBox.setMinimum(75)
        self.FrameDuration_SpinBox.setMaximum(1000)
        self.FrameDuration_SpinBox.setValue(200)
        self.FrameDuration_Label = QLabel(self.FrameDuration_Frame)
        self.FrameDuration_Label.setObjectName(u"FrameDuration_Label")
        self.FrameDuration_Label.setGeometry(QRect(10, 5, 120, 20))
        self.FrameDuration_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.FrameDuration_Label.setIndent(-1)
        self.UpdateInterval_Frame = QFrame(self.Prameters_GroupBox)
        self.UpdateInterval_Frame.setObjectName(u"UpdateInterval_Frame")
        self.UpdateInterval_Frame.setEnabled(True)
        self.UpdateInterval_Frame.setGeometry(QRect(10, 80, 320, 30))
        self.UpdateInterval_Frame.setFrameShape(QFrame.NoFrame)
        self.UpdateInterval_Frame.setFrameShadow(QFrame.Plain)
        self.UpdateInterval_HorizontalSlider = QSlider(self.UpdateInterval_Frame)
        self.UpdateInterval_HorizontalSlider.setObjectName(u"UpdateInterval_HorizontalSlider")
        self.UpdateInterval_HorizontalSlider.setGeometry(QRect(140, 5, 100, 20))
        self.UpdateInterval_HorizontalSlider.setMinimum(0)
        self.UpdateInterval_HorizontalSlider.setMaximum(100)
        self.UpdateInterval_HorizontalSlider.setSliderPosition(100)
        self.UpdateInterval_HorizontalSlider.setOrientation(Qt.Horizontal)
        self.UpdateInterval_SpinBox = QSpinBox(self.UpdateInterval_Frame)
        self.UpdateInterval_SpinBox.setObjectName(u"UpdateInterval_SpinBox")
        self.UpdateInterval_SpinBox.setGeometry(QRect(250, 5, 60, 20))
        self.UpdateInterval_SpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.UpdateInterval_SpinBox.setSpecialValueText(u"")
        self.UpdateInterval_SpinBox.setMinimum(0)
        self.UpdateInterval_SpinBox.setMaximum(100)
        self.UpdateInterval_Label = QLabel(self.UpdateInterval_Frame)
        self.UpdateInterval_Label.setObjectName(u"UpdateInterval_Label")
        self.UpdateInterval_Label.setGeometry(QRect(10, 5, 120, 20))
        self.UpdateInterval_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.UpdateInterval_Label.setIndent(-1)
        self.TaskName_Frame = QFrame(NI9234)
        self.TaskName_Frame.setObjectName(u"TaskName_Frame")
        self.TaskName_Frame.setGeometry(QRect(10, 10, 341, 40))
        self.TaskName_Frame.setFrameShape(QFrame.StyledPanel)
        self.TaskName_Frame.setFrameShadow(QFrame.Raised)
        self.TaskName_Label = QLabel(self.TaskName_Frame)
        self.TaskName_Label.setObjectName(u"TaskName_Label")
        self.TaskName_Label.setGeometry(QRect(10, 10, 60, 20))
        self.TaskName_Label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TaskName_LineEdit = QLineEdit(self.TaskName_Frame)
        self.TaskName_LineEdit.setObjectName(u"TaskName_LineEdit")
        self.TaskName_LineEdit.setGeometry(QRect(80, 10, 251, 20))
        self.ControlButtons_GroupBox = QGroupBox(NI9234)
        self.ControlButtons_GroupBox.setObjectName(u"ControlButtons_GroupBox")
        self.ControlButtons_GroupBox.setGeometry(QRect(370, 0, 261, 51))
        self.StartRecord_PushButton = QPushButton(self.ControlButtons_GroupBox)
        self.StartRecord_PushButton.setObjectName(u"StartRecord_PushButton")
        self.StartRecord_PushButton.setGeometry(QRect(10, 20, 75, 24))
        self.StopRecord_PushButton = QPushButton(self.ControlButtons_GroupBox)
        self.StopRecord_PushButton.setObjectName(u"StopRecord_PushButton")
        self.StopRecord_PushButton.setGeometry(QRect(180, 20, 75, 24))
        self.PauseRecord_PushButton = QPushButton(self.ControlButtons_GroupBox)
        self.PauseRecord_PushButton.setObjectName(u"PauseRecord_PushButton")
        self.PauseRecord_PushButton.setGeometry(QRect(100, 20, 75, 24))
        self.Parameters_Label = QLabel(NI9234)
        self.Parameters_Label.setObjectName(u"Parameters_Label")
        self.Parameters_Label.setEnabled(True)
        self.Parameters_Label.setGeometry(QRect(20, 380, 191, 181))
        self.Parameters_Label.setWordWrap(False)
        self.Parameters_Label.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)
        self.layoutWidget = QWidget(NI9234)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(760, 70, 371, 631))
        self.spectrum = QVBoxLayout(self.layoutWidget)
        self.spectrum.setSpacing(0)
        self.spectrum.setObjectName(u"spectrum")
        self.spectrum.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.spectrum.setContentsMargins(0, 0, 0, 0)
        self.graphicsView_5 = QGraphicsView(self.layoutWidget)
        self.graphicsView_5.setObjectName(u"graphicsView_5")

        self.spectrum.addWidget(self.graphicsView_5)

        self.graphicsView_6 = QGraphicsView(self.layoutWidget)
        self.graphicsView_6.setObjectName(u"graphicsView_6")

        self.spectrum.addWidget(self.graphicsView_6)

        self.graphicsView_7 = QGraphicsView(self.layoutWidget)
        self.graphicsView_7.setObjectName(u"graphicsView_7")

        self.spectrum.addWidget(self.graphicsView_7)

        self.graphicsView_8 = QGraphicsView(self.layoutWidget)
        self.graphicsView_8.setObjectName(u"graphicsView_8")

        self.spectrum.addWidget(self.graphicsView_8)

        self.widget = QWidget(NI9234)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(370, 70, 381, 631))
        self.wave = QVBoxLayout(self.widget)
        self.wave.setSpacing(0)
        self.wave.setObjectName(u"wave")
        self.wave.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.wave.setContentsMargins(0, 0, 0, 0)
        self.graphicsView = QGraphicsView(self.widget)
        self.graphicsView.setObjectName(u"graphicsView")

        self.wave.addWidget(self.graphicsView)

        self.graphicsView_2 = QGraphicsView(self.widget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")

        self.wave.addWidget(self.graphicsView_2)

        self.graphicsView_3 = QGraphicsView(self.widget)
        self.graphicsView_3.setObjectName(u"graphicsView_3")

        self.wave.addWidget(self.graphicsView_3)

        self.graphicsView_4 = QGraphicsView(self.widget)
        self.graphicsView_4.setObjectName(u"graphicsView_4")

        self.wave.addWidget(self.graphicsView_4)


        self.retranslateUi(NI9234)
        self.SampleRate_HorizontalSlider.valueChanged.connect(self.SampleRate_SpinBox.setValue)
        self.SampleRate_SpinBox.valueChanged.connect(self.SampleRate_HorizontalSlider.setValue)
        self.FrameDuration_HorizontalSlider.valueChanged.connect(self.FrameDuration_SpinBox.setValue)
        self.FrameDuration_SpinBox.valueChanged.connect(self.FrameDuration_HorizontalSlider.setValue)
        self.UpdateInterval_HorizontalSlider.valueChanged.connect(self.UpdateInterval_SpinBox.setValue)
        self.UpdateInterval_SpinBox.valueChanged.connect(self.UpdateInterval_HorizontalSlider.setValue)
        self.DownSample_HorizontalSlider.valueChanged.connect(self.DownSample_SpinBox.setValue)
        self.DownSample_SpinBox.valueChanged.connect(self.DownSample_HorizontalSlider.setValue)

        QMetaObject.connectSlotsByName(NI9234)
    # setupUi

    def retranslateUi(self, NI9234):
        NI9234.setWindowTitle(QCoreApplication.translate("NI9234", u"NI9234", None))
        self.ChannelOption_GroupBox.setTitle(QCoreApplication.translate("NI9234", u"Channel option", None))
        self.Ch4_CheckBox.setText(QCoreApplication.translate("NI9234", u"Channel 4", None))
        self.Ch4_ComboBox.setItemText(0, QCoreApplication.translate("NI9234", u"Sensor type", None))
        self.Ch4_ComboBox.setItemText(1, QCoreApplication.translate("NI9234", u"Accelerometer", None))
        self.Ch4_ComboBox.setItemText(2, QCoreApplication.translate("NI9234", u"Microphone", None))

        self.Ch2_CheckBox.setText(QCoreApplication.translate("NI9234", u"Channel 2", None))
        self.Ch2_ComboBox.setItemText(0, QCoreApplication.translate("NI9234", u"Sensor type", None))
        self.Ch2_ComboBox.setItemText(1, QCoreApplication.translate("NI9234", u"Accelerometer", None))
        self.Ch2_ComboBox.setItemText(2, QCoreApplication.translate("NI9234", u"Microphone", None))

        self.Ch3_CheckBox.setText(QCoreApplication.translate("NI9234", u"Channel 3", None))
        self.Ch3_ComboBox.setItemText(0, QCoreApplication.translate("NI9234", u"Sensor type", None))
        self.Ch3_ComboBox.setItemText(1, QCoreApplication.translate("NI9234", u"Accelerometer", None))
        self.Ch3_ComboBox.setItemText(2, QCoreApplication.translate("NI9234", u"Microphone", None))

        self.Ch1_CheckBox.setText(QCoreApplication.translate("NI9234", u"Channel 1", None))
        self.Ch1_ComboBox.setItemText(0, QCoreApplication.translate("NI9234", u"Sensor type", None))
        self.Ch1_ComboBox.setItemText(1, QCoreApplication.translate("NI9234", u"Accelerometer", None))
        self.Ch1_ComboBox.setItemText(2, QCoreApplication.translate("NI9234", u"Microphone", None))

        self.Prameters_GroupBox.setTitle(QCoreApplication.translate("NI9234", u"Parameters", None))
        self.SampleRate_Label.setText(QCoreApplication.translate("NI9234", u"Sampling Rate (Hz)", None))
        self.DownSample_Label.setText(QCoreApplication.translate("NI9234", u"Graph Down Sample", None))
        self.FrameDuration_Label.setText(QCoreApplication.translate("NI9234", u"Frame Duration (ms)", None))
        self.UpdateInterval_Label.setText(QCoreApplication.translate("NI9234", u"Update Interval (ms)", None))
        self.TaskName_Label.setText(QCoreApplication.translate("NI9234", u"Task Name", None))
        self.ControlButtons_GroupBox.setTitle(QCoreApplication.translate("NI9234", u"Control", None))
        self.StartRecord_PushButton.setText(QCoreApplication.translate("NI9234", u"Start", None))
        self.StopRecord_PushButton.setText(QCoreApplication.translate("NI9234", u"Stop", None))
        self.PauseRecord_PushButton.setText(QCoreApplication.translate("NI9234", u"Pause", None))
        self.Parameters_Label.setText(QCoreApplication.translate("NI9234", u"<html><head/><body><p>Parameters!!</p><p>Will show at here!!</p></body></html>", None))
    # retranslateUi

